### ISSUE TITLE
Make it compatible with iPhone

### ISSUE THREAD

**Issue by DonavanMartin** [webdevsk/FB-Mobile-Clean-my-feeds#1]
Hi,

Can someone check if this script that I did for iPhone with multi language is compatible with Android?
https://github.com/DonavanMartin/FB-Iphone-Clean-my-feeds/blob/main/FB%20iPhone%20-%20Clean%20my%20feeds.user.js

If it's works I will make a pull request otherwise maybe I can check to make it compatible.

Best regards

**Comment by webdevsk** [comment]
Dear [DonavanMartin](https://github.com/DonavanMartin),

Thank you for your interest and contribution to this script. Your efforts are much appreciated.

### iPhone support
I suppose we can make it work on iPhones by adding a match for `www.fb`?
If that's the case, we need to make sure that this script does not execute on Desktop browsers as well. Some users may have their scripts synced between Desktop and Phones given that they use the same script manager. See if you can add a check to return/terminate this script on Desktop versions of FB.

You may add a conditional check for desktop version here:
https://github.com/webdevsk/FB-Mobile-Clean-my-feeds/blob/2f01e90a6f00bfc4205f8431de94bf4901b91972/FB%20Mobile%20-%20Clean%20my%20feeds.user.js#L30

### Languages
Thanks for adding new languages. But we have a core problem to solve first.
We are checking `navigator.languages` array for languages a user may use. But this array is not updated by the site as expected. You can check by changing your default language. Even after the change, the array may not update properly. At least on android versions.

While I appreciate your willingness to tackle this problem, let's keep it on hold for now until we find a reliable solution.

### Uncategorized
I noticed that you skipped checking for posts under the "Uncategorized" category. If the reason is the lack of literals for those languages, we can skip it for the time being. Please provide more information if there's another reason behind this decision.

### window.onload
Is this function assignment necessary on iPhone?
This userscript has `// @run-at      document-end` in the header so it runs after document loads anyway. So we can avoid having an extra indentation.

### Conclusion
Thats all the changes I've noticed so far. Please let me know if I have missed any. 

For now, I recommend creating a pull request that includes the desktop version check without modifying the source code. Once merged, we can address other issues as needed.

Thank you again for your contribution. Looking forward to your pull request.

Regards,
[webdevsk](https://github.com/webdevsk)

**Comment by webdevsk** [comment]
No response
